atmel-rf-driver.lib
main.cpp
mbed_app.json
mcr20a-rf-driver.lib

* Updating example to use runtime configuration for RF driver
* Merge after atmel and mcr20a merged (PR's opened by Russ on both drivers)

[ONME-2808] Runtime RF Driver Integration

---

README.md
main.cpp
mbed-os.lib
mbed_app.json
mcr20a-rf-driver.lib

* mbed_app.json can be used to select a particular driver.
* .lib file for mcr20a added
* release candidte

[ONME-2808] Runtime RF DRV Integration & App update

---

main.cpp
mbed_app.json

Add the ncs36510 as a configuration option. Also decrease the heap
size to 10K to allow the code to fit.

Add support for the ncs36510

---

Jenkinsfile

Change node label linux_test to mesh-test

Node label change in Jenkinsfile

---

Jenkinsfile
mbed_app.json

@SeppoTakalo @kimlep01 Please review.

Enabled traces and pan id filter to 6lowpan jenkins builds

---

Jenkinsfile

Define border router channel and panid for CI testing.

Update JenkinsFile to use CI border router

---

README.md

Thread Commissioning configuration described
adding mbed TLS configuration explained

thread commissioning configuration described

---

main.cpp
send_over_tcp_host.py
send_over_udp.py
socket_example.cpp
socket_example.h

Add UDP and TCP example

---

Jenkinsfile
mcr20a-rf-driver.lib

KW24D needs modifications to `mbed_app.json`
* Mesh heap size to 12kB
* Minimal mbed TLS config
* Minimal event-loop heap size.

Add KW24D to CI builds.

---

atmel-rf-driver.lib
mcr20a-rf-driver.lib

driver driver lib update

---

mbed_app.json

root level .json updated

---

main.cpp

Asserts replaced with warnings

Asserts replaced with warnings

---

main.cpp

This fixes the error message mentioned in https://github.com/ARMmbed/mbed-os-example-mesh-minimal/issues/96

Clear up the error message about pin configurations.

---

mbed_app.json

Updated mbed_app.json to include button and LED mappings for KW24D

Updated mbed_app.json to include button and LED mappings for KW24D

---

main.cpp

Something that is missing from our app examples.

Add mbed-trace mutex

---

mesh_led_control_example.cpp

If button is used then it is defined with pull-up

Define pull-up mode for button

---

mesh_led_control_example.cpp

Appropriate message format created for light messages

Update led control msg

---

Jenkinsfile
main.cpp

-Print application build date and mesh type in startup.
-Minor edit to Jenkinsfile help text

Print application build date

---

README.md

Add more memory optimization info.

---

Hardware.md
Jenkinsfile
README.md
configs/mesh_thread.json

New ram configuration

---

configs/mesh_6lowpan.json
configs/mesh_thread.json
mbed_app.json

Add nanostack configuration option for source based compilations.

Update application configs

---

mesh_led_control_example.cpp

Calling send_message() from timer ISR caused assert. Removed messageTimeout
timer, and used queue to handle timeout and message send.

Use queue to send control message

---

Jenkinsfile
configs/mesh_6lowpan.json
configs/mesh_thread.json
mbed_app.json

Update mesh configuration for mbed-os-5.7

Update mesh configuration files

---

README.md

Move configuration section before build section.
Clarify the usage of example configuration files.
This fixes #153 and #152 
@MarceloSalazar and @AnotherButler Please review.

Clarify the README.md

---

README.md

Added link to thread commissioning documentation in os.mbed.com/docs

Updates to thread commissioning documentation

---

main.cpp
mesh_nvm.cpp
mesh_nvm.h
sd-driver.lib

Allow Thread devices to store content to NVM.

Enable NVM for Thread devices

---

README.md
configs/mesh_thread.json
mesh_nvm.cpp

-Allow NVM storage device selection from mesh_thread.json
-Describe Thread NVM usage in README

Update Thread storage device config

---

README.md
atmel-rf-driver.lib
mcr20a-rf-driver.lib
sd-driver.lib

-Remove file system know issue as it is fixed in mbed-os-5.9.1
-Update drivers to the latest version

Update libraries and README

---

README.md

Add more accurete information to known issue.

Update README known issues

---

atmel-rf-driver.lib
configs/mesh_thread.json
main.cpp
sd-driver.lib

-Update RF and SD drivers to the latest version
-Add Thread EUI64 trace to the application
-Update Thread config to use static config (easy to change value later)

Update libraries and traces

---

mcr20a-rf-driver.lib

Updated driver includes fix for EUI64 read problem.

Update MCR20 RF-driver

---

Jenkinsfile
README.md
atmel-rf-driver.lib
mcr20a-rf-driver.lib

After 5.10 these drivers will be provided by Mbed OS

Remove external RF drivers

---

Jenkinsfile
README.md
sd-driver.lib

Also SD driver needs to be removed.
Known issues removed from README.

Remove sd-driver and update README

---

Jenkinsfile
README.md
atmel-rf-driver.lib
mcr20a-rf-driver.lib
sd-driver.lib

Build problems on 5.10, so removing changes from #212 and #213 from master.

Revert 5.10-specific changes from master

---

mbed-os.lib

Updating mbed-os to mbed-os-5.10.0-rc2

Updating mbed-os to mbed-os-5.10.0-rc2

---

mbed-os.lib

Update mbed-os to 5.10.0-rc3

---

Hardware.md
Jenkinsfile
configs/mesh_6lowpan.json
configs/mesh_thread.json
mbed_app.json

-Add KW41Z pin config to config files
-Add KW41Z to Jenkinsfile
-Add KW41Z to hardware readme

Enable support KW41Z

---

configs/mesh_6lowpan.json
configs/mesh_6lowpan_ATMEL.json
configs/mesh_6lowpan_MCR20A.json
configs/mesh_thread.json
configs/mesh_thread_ATMEL.json
configs/mesh_thread_MCR20A.json
configs/mesh_wisun_S2LP.json
mbed_app.json
mesh_led_control_example.cpp

mesh_led_control_example is using digital output to control relay with K64F.
configuration json files changed to make it configurable.
Also new config file for wisun created.

Configuration json files changed to make relay control configurable

---

Jenkinsfile

* Fixed smoke test trying to unstash not built combinations
* Use Raas names instead of ports + https
* Enabled smoke tests by default

Fixed smoke test

---

README.md

Checke…d and default configuration works. Connection can take long time, up yo 15 minutes.
Updated README.md with information about time needed to connect.
@JarkkoPaso 
@mikter 
@SeppoTakalo

OOB - WiSUN example never connects with default configuration.

---

.travis.yml
CMakeLists.txt
mbed-os.lib

This pull request updates the example to be compatible with the 
mbed-os-6.6.0 release of mbed-os.

Update for mbed-os-6.6.0
