ARMmbed/mbed-os-example-mesh-minimal

Jenkinsfile
Build against different mbed-os revisions & hw smoke
* Added ability to build against different mbed-os branches (default being master)
- Triggered from Jenkins "Build with parameters"
* Removed non compatible Ublox & mcr20 build combination
* Added a simple hw smoke test as the final stage with K64F & atmel combination
- Smoke test is not 100% reliable yet (ONME-2882).
@SeppoTakalo @artokin
=> Build against different mbed-os revisions & hw smoke

Jenkinsfile
Enable F401RE for gcc and armcc
* NUCLEO_F401RE built with gcc and armcc
(IAR build skipped with a simple if statement)
@artokin @SeppoTakalo
=> Enable F401RE for gcc and armcc

Jenkinsfile
The first PR build always fails due to parameters missing, this should fix the behaviour.
=> Fix jenkinsfile parameter usage

configs/mesh_6lowpan.json, configs/mesh_thread.json, main.cpp, mbed_app.json
Although KW24D uses the same MCR20A driver, it is nice to explicitly list KW24D as supported and make it easy for users to choose it in the application if they like.
=> Add support for KW24D

mbed_app.json
Add to target overrides for NCS36510 LED and BUTTON macros used in the example.
=> Add NCS36510 definitions for led control example

Jenkinsfile
Application Thread device type changed to MED from of ROUTER.
Router device generates address automatically and therefore border
router connection was not needed. With MED device type border router
is needed to get device bootstrapped.
Note! Thsi change requires mbed-os-5.5
=> Thread device type changed to MED

atmel-rf-driver.lib, main.cpp, mcr20a-rf-driver.lib
[Warning] #1293-D: assignment in condition
[Warning] #177-D: function "serial_out_mutex_wait"  was declared
but never referenced
[Warning] #177-D: function "serial_out_mutex_release"  was declared
but never referenced
=> [ONME-3113] Fix ARM compiler warnings

README.md
The mbed (atmel based) gateway is considered deprecated (for 5.6 onwards), as there is no (public) source source code nor mbed Enabled.
@SeppoTakalo
=> Remove mbed gateway

mbed_app.json
The LED is in the same pin as SPI1_SCK and therefore cannot be
used with radio shield.
Fixes #126
=> Fix led pin collision with NUCLEO_F401RE and NUCLEO_F411RE

mesh_led_control_example.cpp
ff03::1 is not good for multicast address.
please refer [the issue details at here](https://github.com/ARMmbed/mbed-os-example-mesh-minimal/issues/130).
=> Fix an incorrect multicast address.

mesh_led_control_example.cpp
Do not rely on any default multicast groups to be enabled.
Don't spam nodes which have not joined our group.
Fixes #130
This needs to be manually tested for both Thread and 6LoWPAN.
=> Make our own multicast group and join it.

configs/mesh_6lowpan.json, configs/mesh_thread.json
In nucleo board, LED_RED pin is overlapping with radio shield SPI. Removing led
from configuration.
=> Removed led from nucleo F401RE configuration

mesh_nvm.cpp
Nanostack initialisation will occur after the first call to:
Nanostack::get_instance
Set file system root path after Nanostack initialisation.
=> Ensure Nanostack is initialised before using it

README.md
Fixed two links to point to updated locations and added workaround for https://github.com/ARMmbed/mbed-os-example-mesh-minimal/issues/188
=> Fixed broken links and added known issue for Mbed OS 5.9

mbedtls_config.h
-Limit number of MBEDTLS in/out buffers to 4kB instead of 16kB
-Limit number of max entropy sources to 4
=> Optimize MBEDTLS configuration

configs/mesh_6lowpan.json, configs/mesh_thread.json, mbed_app.json, mesh_led_control_example.cpp
NUCLEO_F429ZI features an user button which needs the mode to be PullDown instead of PullUp. The configuration defaults to PullUp and can be overridden.
Related issue: https://github.com/ARMmbed/mbed-os-example-mesh-minimal/issues/193
=> Add a configuration option for button mode

main.cpp
Thread EUI64 tracing will be supported in Mbed OS 5.10.
=> Add Mbed OS version check to Thread EUI64 trace

Jenkinsfile
Use 15k heap for all KW24D mesh configurations to avoid occasional
test failures due low memory.
=> Update Jenkinsfile for KW24D

Hardware.md, README.md, configs/mesh_wisun_S2LP.json
Added note on the wire jumper for wi-sun shield.
Fixed configuration for wi-sun.
Added missing link explaining backhaul configurations.
Changed ".json" to "mbed_app.json" to avoid ambiguity.
Adresses issues #263, #264, #265, #266, #267
=> Fixes in README.md and wisun config

README.md
Fixes https://github.com/ARMmbed/mbed-os-example-mesh-minimal/issues/260
Fixes https://github.com/ARMmbed/mbed-os-example-mesh-minimal/issues/262
The tables were rewritten as @korjaa did in https://github.com/ARMmbed/mbed-os-example-mesh-minimal/pull/261.
=> Refresh tables contents and fix broken link

main.cpp
String-based APIs were marked deprecated and replaced by `SocketAddress`-based APIs in https://github.com/ARMmbed/mbed-os/pull/11914.
This PR switches the example to the new API and removes the deprecated one.
To get this compile I updated `mbed-os.lib` to 5.15.
=> Remove deprecated string-based API

main.cpp
This is to include the string-based API deprecation in the 5.15 release. This will allow us to pass CI checks in https://github.com/ARMmbed/mbed-os/pull/11942, which removes the deprecated API and is required for the upcoming mbed-os-6 release.
=> Include deprecated API removal in the mbed-os-5.15 branch

.travis.yml, CMakeLists.txt, mbed-os.lib
- Added CMakeLists.txt file to mesh minimal example so that it can build via CMake
- Added .travis.yml config to pick this example for Travis CI build
- Update mbed-os.lib to latest master to pick CMake changes
Preceding PR# https://github.com/ARMmbed/mbed-os/pull/13953
@0xc0170 @hugueskamba
=> Add CMake support

.travis.yml, CMakeLists.txt, README.md
Remove deprecated CMake functions.
Update travis.yml with new mbed-tools commands.
Update README.md with mbed-tools instructions.
Depends on https://github.com/ARMmbed/mbed-os/pull/14546
Fixes #331
=> Fix mbed-tools support

configs/mesh_6lowpan.json, configs/mesh_6lowpan_ATMEL.json, configs/mesh_6lowpan_MCR20A.json, configs/mesh_thread.json, configs/mesh_thread_ATMEL.json, configs/mesh_thread_MCR20A.json, configs/mesh_wisun_S2LP.json, mbed_app.json
This PR updates this example to use the new Arduino pin names (e.g. D0 -> ARDUINO_UNO_D0).
=> Update Arduino pin names
